# Weather Data per State week 40 2010 to week 49 2019

In [1]:
# import libaries

# import pandas and numpy for data manipulation and exploratory data analysis (set up for complete view on data)
import pandas as pd
import numpy as np

# importing matplotlib and seaborn for visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Import weather data
alabama = pd.read_csv('data/Alabama.txt')

In [3]:
alaska = pd.read_csv('data/Alaska.txt')

In [4]:
# filter data only for Fairbanks Airport
alaska1 = alaska[(alaska['NAME']=='FAIRBANKS INTERNATIONAL AIRPORT, AK US')]

In [5]:
aac = pd.read_csv('data/Arizona-Arkansas-California.txt')

In [6]:
ci = pd.read_csv('data/Colorado-Iowa.txt')

In [7]:
kw = pd.read_csv('data/Kansas-Wyoming.txt')

In [8]:
# merge data
frames = [alabama, alaska1, aac, ci, kw]
weather = pd.concat(frames, sort=True)

In [9]:
weather.tail(3)

,AWND,DATE,NAME,PRCP,SNOW,SNWD,STATION,TAVG,TMAX,TMIN,...,WT11,WT13,WT14,WT15,WT16,WT17,WT18,WT19,WT21,WT22
125612,12.08,2019-12-04,"JFK INTERNATIONAL AIRPORT, NY US",0.0,0.0,0.0,USW00094789,36.0,39.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125613,NaN,2019-12-05,"JFK INTERNATIONAL AIRPORT, NY US",0.0,0.0,0.0,USW00094789,40.0,44.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125614,NaN,2019-12-06,"JFK INTERNATIONAL AIRPORT, NY US",NaN,NaN,NaN,USW00094789,40.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
weather.shape

(179981, 30)

In [11]:
missing_val = weather.isnull().sum()
print(missing_val)

AWND         3599
DATE            0
NAME            0
PRCP          191
SNOW        49738
SNWD        54196
STATION         0
TAVG        95379
TMAX         3248
TMIN         3259
WT01       124510
WT02       173109
WT03       163812
WT04       178927
WT05       176100
WT06       179145
WT07       178758
WT08       158610
WT09       178954
WT10       179942
WT11       179735
WT13       166410
WT14       177592
WT15       179880
WT16       163195
WT17       179850
WT18       175141
WT19       179803
WT21       179611
WT22       179315
dtype: int64

In [12]:
to_drop = ['TAVG','WT01','WT02','WT03','WT04','WT05','WT06','WT07','WT08','WT09','WT10','WT11','WT13','WT14','WT15','WT16','WT17','WT18','WT19','WT21','WT22']       
weather.drop(columns=to_drop,inplace=True,axis=1)

In [13]:
weather.shape

(179981, 9)

In [14]:
weather.dtypes

AWND       float64
DATE        object
NAME        object
PRCP       float64
SNOW       float64
SNWD       float64
STATION     object
TMAX       float64
TMIN       float64
dtype: object

In [15]:
# convert data object to type datetime
weather['DATE'] =  pd.to_datetime(weather['DATE'])

In [16]:
weather.dtypes

AWND              float64
DATE       datetime64[ns]
NAME               object
PRCP              float64
SNOW              float64
SNWD              float64
STATION            object
TMAX              float64
TMIN              float64
dtype: object

In [17]:
weather.shape

(179981, 9)

In [18]:
# 50 states of US
weather['NAME'].nunique()

50

In [19]:
# filter data from week 1 in 2010 to week 48 in 2019
weather = weather[(weather['DATE'] > '2010-10-03') & (weather['DATE'] < '2019-12-02')]

In [20]:
weather.head(5)

,AWND,DATE,NAME,PRCP,SNOW,SNWD,STATION,TMAX,TMIN
276,6.04,2010-10-04,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,69.0,41.0
277,5.37,2010-10-05,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,73.0,39.0
278,3.80,2010-10-06,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,78.0,41.0
279,2.91,2010-10-07,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,86.0,45.0
280,1.12,2010-10-08,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,89.0,53.0

In [21]:
weather.tail(5)

,AWND,DATE,NAME,PRCP,SNOW,SNWD,STATION,TMAX,TMIN
125605,NaN,2019-11-27,"JFK INTERNATIONAL AIRPORT, NY US",0.01,0.0,0.0,USW00094789,56.0,44.0
125606,NaN,2019-11-28,"JFK INTERNATIONAL AIRPORT, NY US",0.00,0.0,0.0,USW00094789,53.0,37.0
125607,NaN,2019-11-29,"JFK INTERNATIONAL AIRPORT, NY US",0.00,0.0,0.0,USW00094789,41.0,30.0
125608,10.96,2019-11-30,"JFK INTERNATIONAL AIRPORT, NY US",0.00,0.0,0.0,USW00094789,44.0,30.0
125609,14.32,2019-12-01,"JFK INTERNATIONAL AIRPORT, NY US",0.59,0.0,0.0,USW00094789,41.0,29.0

In [22]:
# check if data is complete - from 04.01.2010 to 01.12.2019 = 3619 days * 50 states = 180950 rows expected -> 1349 rows are missing
weather.shape

(166157, 9)

In [23]:
missing_val = weather.isnull().sum()
print(missing_val)

AWND        3412
DATE           0
NAME           0
PRCP         151
SNOW       44673
SNWD       48535
STATION        0
TMAX        3130
TMIN        3141
dtype: int64

In [24]:
# all states are still represented
weather['NAME'].nunique()

50

In [25]:
# check for unique weather days 
weather['DATE'].nunique()

3346

In [26]:
weather.head(5)

,AWND,DATE,NAME,PRCP,SNOW,SNWD,STATION,TMAX,TMIN
276,6.04,2010-10-04,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,69.0,41.0
277,5.37,2010-10-05,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,73.0,39.0
278,3.80,2010-10-06,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,78.0,41.0
279,2.91,2010-10-07,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,86.0,45.0
280,1.12,2010-10-08,"BIRMINGHAM AIRPORT, AL US",0.0,0.0,0.0,USW00013876,89.0,53.0

In [27]:
weather_week = weather.groupby(['NAME',pd.Grouper(freq='W', key='DATE')]).mean()

In [28]:
weather_week.reset_index(inplace=True)

In [29]:
weather_week.head(5)

,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN
0,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-10,6.967143,0.001429,0.0,0.0,76.571429,54.142857
1,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-17,5.208571,0.000000,0.0,0.0,74.857143,49.428571
2,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-24,7.287143,0.024286,0.0,0.0,68.285714,47.857143
3,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-31,8.084286,0.000000,0.0,0.0,65.714286,39.714286
4,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-11-07,6.070000,0.000000,0.0,0.0,67.000000,42.142857

In [30]:
weather_week['NAME'].nunique()

50

In [31]:
stations = pd.read_excel('data/weather_station_dict.xlsx')

In [32]:
stations_dict = dict(zip(stations['Weather Station'],stations['State']))

In [33]:
weather_week['STATE'] = weather_week['NAME'].map(stations_dict)

In [34]:
weather_week.head(60)

,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN,STATE
0,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-10,6.967143,0.001429,0.000000,0.000000,76.571429,54.142857,New Mexico
1,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-17,5.208571,0.000000,0.000000,0.000000,74.857143,49.428571,New Mexico
2,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-24,7.287143,0.024286,0.000000,0.000000,68.285714,47.857143,New Mexico
3,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-31,8.084286,0.000000,0.000000,0.000000,65.714286,39.714286,New Mexico
4,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-11-07,6.070000,0.000000,0.000000,0.000000,67.000000,42.142857,New Mexico
5,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-11-14,6.328571,0.000000,0.000000,0.000000,55.714286,31.857143,New Mexico
6,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-11-21,7.382857,0.000000,0.000000,0.000000,59.285714,33.142857,New Mexico
7,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-11-28,8.884286,0.002857,0.042857,0.000000,49.571429,25.000000,New Mexico
8,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-12-05,4.825714,0.000000,0.000000,0.000000,52.285714,28.142857,New Mexico
9,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-12-12,5.721429,0.000000,0.000000,0.000000,56.428571,30.857143,New Mexico
10,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-12-19,6.134286,0.138571,0.157143,0.000000,53.857143,33.142857,New Mexico
11,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-12-26,4.730000,0.011429,0.000000,0.000000,52.142857,35.571429,New Mexico
12,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-01-02,7.732857,0.002857,0.085714,0.000000,37.857143,19.428571,New Mexico
13,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-01-09,6.040000,0.000000,0.000000,0.000000,45.857143,22.714286,New Mexico
14,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-01-16,6.454286,0.000000,0.000000,0.000000,46.142857,22.857143,New Mexico
15,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-01-23,8.117143,0.000000,0.000000,0.000000,54.285714,31.142857,New Mexico
16,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-01-30,4.442857,0.000000,0.000000,0.000000,51.285714,24.857143,New Mexico
17,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-02-06,11.601429,0.015714,0.114286,0.142857,32.857143,10.714286,New Mexico
18,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-02-13,6.231429,0.000000,0.000000,0.000000,48.714286,18.285714,New Mexico
19,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-02-20,7.317143,0.000000,0.000000,0.000000,64.000000,36.142857,New Mexico
20,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-02-27,7.702857,0.000000,0.000000,0.000000,55.714286,30.285714,New Mexico
21,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-03-06,6.742857,0.000000,0.000000,0.000000,61.428571,31.000000,New Mexico
22,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-03-13,8.500000,0.000000,0.000000,0.000000,65.285714,38.571429,New Mexico
23,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-03-20,7.541429,0.000000,0.000000,0.000000,73.000000,43.000000,New Mexico
24,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-03-27,10.227143,0.000000,0.000000,0.000000,66.285714,38.714286,New Mexico
25,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-04-03,11.248571,0.000000,0.000000,0.000000,74.428571,44.285714,New Mexico
26,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-04-10,12.878571,0.004286,0.000000,0.000000,68.142857,43.000000,New Mexico
27,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-04-17,9.970000,0.000000,0.000000,0.000000,71.571429,40.857143,New Mexico
28,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-04-24,11.537143,0.000000,0.000000,0.000000,77.142857,54.000000,New Mexico
29,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-05-01,14.700000,0.000000,0.000000,0.000000,67.000000,41.285714,New Mexico
30,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-05-08,6.485714,0.000000,0.000000,0.000000,77.428571,45.000000,New Mexico
31,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-05-15,13.487143,0.000000,0.000000,0.000000,76.857143,47.142857,New Mexico
32,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-05-22,9.875714,0.007143,0.000000,0.000000,73.857143,46.428571,New Mexico
33,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-05-29,12.365714,0.000000,0.000000,0.000000,86.000000,56.857143,New Mexico
34,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-06-05,11.505714,0.000000,0.000000,0.000000,89.714286,60.571429,New Mexico
35,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-06-12,7.061429,0.000000,0.000000,0.000000,91.285714,59.142857,New Mexico
36,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-06-19,9.905714,0.000000,0.000000,0.000000,93.571429,61.857143,New Mexico
37,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-06-26,8.437143,0.000000,0.000000,0.000000,94.857143,63.000000,New Mexico
38,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-07-03,9.781429,0.000000,0.000000,0.000000,96.000000,69.571429,New Mexico
39,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-07-10,6.612857,0.000000,0.000000,0.000000,96.000000,69.285714,New Mexico
40,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-07-17,7.861429,0.000000,0.000000,0.000000,93.428571,68.285714,New Mexico
41,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-07-24,6.932857,0.045714,0.000000,0.000000,96.000000,70.714286,New Mexico
42,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-07-31,8.788571,0.010000,0.000000,0.000000,92.285714,68.000000,New Mexico
43,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-08-07,5.941429,0.017143,0.000000,0.000000,94.285714,68.285714,New Mexico
44,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-08-14,7.285714,0.000000,0.000000,0.000000,95.142857,69.714286,New Mexico
45,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-08-21,8.437143,0.045714,0.000000,0.000000,90.571429,67.571429,New Mexico
46,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-08-28,5.751429,0.054286,0.000000,0.000000,94.428571,68.571429,New Mexico
47,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-09-04,8.371429,0.028571,0.000000,0.000000,92.142857,66.857143,New Mexico
48,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-09-11,9.554286,0.030000,0.000000,0.000000,79.428571,60.428571,New Mexico
49,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-09-18,6.167143,0.014286,0.000000,0.000000,78.714286,55.571429,New Mexico
50,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-09-25,5.625714,0.000000,0.000000,0.000000,84.857143,55.571429,New Mexico
51,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-10-02,7.511429,0.000000,0.000000,0.000000,84.000000,57.857143,New Mexico
52,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-10-09,8.085714,0.205714,0.000000,0.000000,65.857143,47.142857,New Mexico
53,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-10-16,4.475714,0.000000,0.000000,0.000000,77.000000,47.142857,New Mexico
54,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-10-23,5.592857,0.000000,0.000000,0.000000,73.714286,45.714286,New Mexico
55,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-10-30,6.932857,0.005714,0.000000,0.000000,67.000000,42.000000,New Mexico
56,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-11-06,7.637143,0.011429,0.000000,0.000000,61.000000,37.000000,New Mexico
57,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-11-13,6.551429,0.001429,0.000000,0.000000,54.000000,34.142857,New Mexico
58,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-11-20,5.975714,0.000000,0.000000,0.000000,59.714286,36.857143,New Mexico
59,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2011-11-27,6.357143,0.005714,0.000000,0.000000,55.428571,33.571429,New Mexico

In [35]:
array = weather_week['DATE'].unique()

In [36]:
#array

In [37]:
df_from_arr = pd.DataFrame(data=array)

In [38]:
#df_from_arr

In [39]:
#df_from_arr.to_excel('data/unique_dates.xlsx', index=False)

In [40]:
weeks = pd.read_excel('data/unique_dates.xlsx')

In [41]:
weeks.columns

Index(['DATE', 'WEEK'], dtype='object')

In [42]:
weeks_dict = dict(zip(weeks['DATE'],weeks['WEEK']))

In [43]:
weather_week['WEEK'] = weather_week['DATE'].map(weeks_dict)

In [44]:
year = pd.read_excel('data/unique_year_week.xlsx')

In [45]:
year.columns

Index(['DATE', 'YEAR'], dtype='object')

In [46]:
year_dict = dict(zip(year['DATE'],year['YEAR']))

In [47]:
weather_week['YEAR'] = weather_week['DATE'].map(year_dict)

In [48]:
weather_week.head(5)

,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN,STATE,WEEK,YEAR
0,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-10,6.967143,0.001429,0.0,0.0,76.571429,54.142857,New Mexico,40,2010
1,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-17,5.208571,0.000000,0.0,0.0,74.857143,49.428571,New Mexico,41,2010
2,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-24,7.287143,0.024286,0.0,0.0,68.285714,47.857143,New Mexico,42,2010
3,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-10-31,8.084286,0.000000,0.0,0.0,65.714286,39.714286,New Mexico,43,2010
4,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",2010-11-07,6.070000,0.000000,0.0,0.0,67.000000,42.142857,New Mexico,44,2010

In [49]:
weather_week.tail(5)

,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN,STATE,WEEK,YEAR
23752,"WILMINGTON NEW CASTLE CO AIRPORT, DE US",2019-11-03,7.924286,0.161429,0.0,0.0,63.000000,44.571429,Delaware,45,2019
23753,"WILMINGTON NEW CASTLE CO AIRPORT, DE US",2019-11-10,6.457143,0.011429,0.0,0.0,55.000000,32.571429,Delaware,46,2019
23754,"WILMINGTON NEW CASTLE CO AIRPORT, DE US",2019-11-17,9.491429,0.012857,0.0,0.0,49.714286,27.857143,Delaware,47,2019
23755,"WILMINGTON NEW CASTLE CO AIRPORT, DE US",2019-11-24,7.120000,0.141429,0.0,0.0,51.571429,35.857143,Delaware,48,2019
23756,"WILMINGTON NEW CASTLE CO AIRPORT, DE US",2019-12-01,7.155000,0.081429,0.0,0.0,52.428571,33.285714,Delaware,49,2019

weather_week = weather_week.to_csv('data/weather_week.csv', index=False)